package scamp

import (
	"bytes"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"encoding/base64"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"net"
	"os" // "encoding/json"
	"sync"
	"sync/atomic"
	"time"
)

func init() {
	initSCAMPLogger()

	// DefaultCache, err := NewServiceCache(cachePath)
	// if err != nil {
	// 	return
	// }

	return
}

const (
	defaultMessageTimeout  = time.Second * 120
	defaultLivenessDirPath = "/backplane/running-services/"
	defaultConfigPath      = "/backplane/etc"
)

// DefaultCache is the default service cache
// TODO: this probably shouldn't be a global variable (or exported)
var DefaultCache *ServiceCache

// ServiceActionFunc represents a service callback
type ServiceActionFunc func(*Message, *Client)

// ServiceAction interface
type ServiceAction struct {
	callback ServiceActionFunc
	crudTags string
	version  int
}

// Options that can be passed at time of service creation
// TODO: after doing so, define defaultServiceOptions (in Init()) to set these values when
// a user doesn't
type Options struct {
	// KeyPath path to service private key
	KeyPath string
	// CertPath path to certificate used for signing
	CertPath string
	// AnnouncePath payload to be signed TODO: this field might not be needed
	AnnouncePath string
	// SOAConfigPath path to the soa.conf file
	// the soa.conf file must include the following keys:
	//	1) discovery.cache_path
	SOAConfigPath string
	// LivenessFilePath in Kubernetes environments, scamp services write an empty file to a
	// designated directory to facilitate auto-scaling
	LivenessFilePath string
}

var defaultServiceOptions = Options{
	KeyPath:          "",
	CertPath:         "",
	AnnouncePath:     "",
	SOAConfigPath:    defaultConfigPath,
	LivenessFilePath: defaultLivenessDirPath,
}

// Service represents a scamp service
type Service struct {
	options     Options
	serviceSpec string
	sector      string
	name        string
	humanName   string

	listener     net.Listener
	listenerIP   net.IP
	listenerPort int

	actions   map[string]*ServiceAction
	isRunning bool

	serveWG sync.WaitGroup // counts active Serve goroutines for GracefulStop

	clientsM sync.Mutex
	clients  []*Client
	cert     tls.Certificate
	pemCert  []byte // just a copy of what was read off disk at tls cert load time

	statsCloseChan      chan bool
	connectionsAccepted uint64
}

// ServiceDesc contains service description fields
type ServiceDesc struct {
	// Sector represents the scamp sector that the service is announced with, i.e. "main",
	// "channel_module", "payment", etc...
	Sector string
	// ServiceSpec contains the service specification used for listening/announcing
	ServiceSpec string
	// HumanName is the human readable name of the service, i.e. "sdk_service",
	// "payment_service", etc...
	HumanName string
	// name is an autogenerated service name, this name is HumanName appended with am 18 byte random
	// string of base64 encoded characters
	name string
}

// merge takes the passed in opts struct and updates nil or empty fields with default values
func (o *Options) merge() {
	if o == nil {
		o = &defaultServiceOptions
	} else {
		if len(o.AnnouncePath) == 0 {
			o.AnnouncePath = defaultServiceOptions.AnnouncePath
		}
		if len(o.CertPath) == 0 {
			o.CertPath = defaultServiceOptions.CertPath
		}
		if len(o.KeyPath) == 0 {
			o.KeyPath = defaultServiceOptions.KeyPath
		}
		if len(o.LivenessFilePath) == 0 {
			o.LivenessFilePath = defaultServiceOptions.LivenessFilePath
		}
		if len(o.SOAConfigPath) == 0 {
			o.SOAConfigPath = defaultServiceOptions.SOAConfigPath
		}
	}
}

// NewService initializes and returns pointer to a new scamp service
func NewService(desc ServiceDesc, opts *Options) (*Service, error) {
	if len(desc.HumanName) > 18 {
		return nil, fmt.Errorf("name `%s` is too long, it must be less than 18 bytes", desc.HumanName)
	}
	opts.merge()

	err := initConfig(opts.SOAConfigPath)
	if err != nil {
		log.Fatal("could not initialize scamp environment: ", err)
	}

	cachePath, ok := DefaultConfig().Get("discovery.cache_path")
	if !ok {
		log.Fatal("no such config param `discovery.cache_path`: this key must be present in soa.conf to use scamp-go")
	}

	cache, err := NewServiceCache(cachePath)
	if err != nil {
		log.Fatalf("couldn't create service cache: %s", err)
	}
	DefaultCache = cache

	// TODO: consider using an alternate certpath/keypath in options
	// override ServiceCertPath/ServiceKeyPath to use opts
	crtPath := DefaultConfig().ServiceCertPath(desc.HumanName)
	keyPath := DefaultConfig().ServiceKeyPath(desc.HumanName)

	// Load keypair for tls socket library to use
	keypair, err := tls.LoadX509KeyPair(string(crtPath), string(keyPath))
	if err != nil {
		return nil, err
	}

	// TODO: move this logic into ServiceOption func
	if crtPath == nil || keyPath == nil {
		err = fmt.Errorf(
			"could not find valid crt/key pair for service %s (`%s`,`%s`)",
			desc.HumanName,
			//TODO: make sure the following fields are properly initialized
			defaultServiceOptions.CertPath,
			defaultServiceOptions.KeyPath,
		)
		return nil, err
	}

	service := &Service{
		sector:      desc.Sector,
		serviceSpec: desc.ServiceSpec,
		humanName:   desc.HumanName,
		actions:     make(map[string]*ServiceAction),
		cert:        keypair,
		pemCert:     loadPEMCertBytes(string(crtPath)),
	}
	service.generateRandomName()

	err = service.listen()
	if err != nil {
		return nil, err
	}

	service.statsCloseChan = make(chan bool)
	return service, nil
}

// loadPEMCertBytes loads certificate file as bytes
func loadPEMCertBytes(filePath string) []byte {
	pemCert, err := ioutil.ReadFile(filePath)
	if err != nil {
		log.Fatal("could not load certificate file")
	}
	return bytes.TrimSpace(pemCert)
}

// TODO: port discovery and interface/IP discovery should happen here
// important to set values so announce packets are correct
func (serv *Service) listen() (err error) {
	config := &tls.Config{
		Certificates: []tls.Certificate{serv.cert},
	}

	Info.Printf("starting service on %s", serv.serviceSpec)
	serv.listener, err = tls.Listen("tcp", serv.serviceSpec, config)
	if err != nil {
		return err
	}
	addr := serv.listener.Addr()
	Info.Printf("service now listening to %s", addr.String())

	// TODO: get listenerIP to return 127.0.0.1 or something other than '::'/nil
	// serv.listenerIP = serv.listener.Addr().(*net.TCPAddr).IP
	serv.listenerIP, err = getIPForAnnouncePacket()
	if err != nil {
		return
	}

	serv.listenerPort = serv.listener.Addr().(*net.TCPAddr).Port
	return
}

// Register registers a service handler callback
func (serv *Service) Register(name string, callback ServiceActionFunc) (err error) {
	if serv.isRunning {
		err = errors.New("cannot register handlers while server is running")
		return
	}

	serv.actions[name] = &ServiceAction{
		callback: callback,
		version:  1,
	}
	return
}

//Run starts a scamp service
func (serv *Service) Run() {
	err := serv.createKubeLivenessFile()
	if err != nil {
		fmt.Println(err)
	}

forLoop:
	for {
		netConn, err := serv.listener.Accept()
		if err != nil {
			// Info.Printf("exiting service Run(): `%s`", err)
			break forLoop
		}
		// Trace.Printf("accepted new connection...")

		//var tlsConn (*tls.Conn) = (netConn).(*tls.Conn)
		tlsConn := (netConn).(*tls.Conn)
		if tlsConn == nil {
			Error.Fatalf("could not create tlsConn")
			break forLoop
		}

		conn := NewConnection(tlsConn, "service")
		client := NewClient(conn, "service")

		serv.clientsM.Lock()
		serv.clients = append(serv.clients, client)
		serv.clientsM.Unlock()

		go serv.Handle(client)

		atomic.AddUint64(&serv.connectionsAccepted, 1)
	}

	// Info.Printf("closing all registered objects")

	serv.clientsM.Lock()
	for _, client := range serv.clients {
		client.Close()
	}
	serv.clientsM.Unlock()

	serv.statsCloseChan <- true
}

//Handle handles incoming client messages received via the cient MessageChan
func (serv *Service) Handle(client *Client) {
	var action *ServiceAction
	//Info.Printf("handling client for remote connection: %s\n", client.conn.conn.RemoteAddr())
HandlerLoop:
	for {
		select {
		case msg, ok := <-client.Incoming():
			if !ok {
				break HandlerLoop
			}
			action = serv.actions[msg.Action]

			if action != nil {
				// Info.Printf("handling action %s\n", action.crudTags)
				action.callback(msg, client)
			} else {
				Error.Printf("do not know how to handle action `%s`", msg.Action)

				reply := NewMessage()
				reply.SetMessageType(MessageTypeReply)
				reply.SetEnvelope(EnvelopeJSON)
				reply.SetRequestID(msg.RequestID)
				reply.Write([]byte(`{"error": "no such action"}`))
				_, err := client.Send(reply)
				if err != nil {
					client.Close()
					break HandlerLoop
				}
			}
		case <-time.After(defaultMessageTimeout):
			break HandlerLoop
		}
	}

	client.Close()
	serv.RemoveClient(client)
}

// RemoveClient removes a client from the scamp service
func (serv *Service) RemoveClient(client *Client) (err error) {
	serv.clientsM.Lock()
	defer serv.clientsM.Unlock()

	index := -1
	for i, entry := range serv.clients {
		if client == entry {
			index = i
			break
		}
	}

	if index == -1 {
		Error.Printf("tried removing client that wasn't being tracked")
		return fmt.Errorf("unknown client") // TODO can I get the client's IP?
	}

	client.Close()
	serv.clients = append(serv.clients[:index], serv.clients[index+1:]...)

	return nil
}

// Stop closes the service's net.Listener
func (serv *Service) Stop() {
	if serv.listener != nil {
		serv.listener.Close()
	}
	fmt.Println("shutting down")
	err := serv.removeKubeLivenessFile()
	if err != nil {
		fmt.Println("could not remove liveness file: ", err)
	}
	fmt.Println("shutdown done")
}

// MarshalText serializes a scamp service
func (serv *Service) MarshalText() (b []byte, err error) {
	var buf bytes.Buffer

	serviceProxy := serviceAsServiceProxy(serv)

	classRecord, err := serviceProxy.MarshalJSON() //json.Marshal(&serviceProxy) //Marshal is mangling service actions
	if err != nil {
		return
	}
	sig, err := signSHA256(classRecord, serv.cert.PrivateKey.(*rsa.PrivateKey))
	if err != nil {
		return
	}
	sigParts := stringToRows(sig, 76)

	buf.Write(classRecord)
	buf.WriteString("\n\n")
	buf.Write(serv.pemCert)
	buf.WriteString("\n\n")
	// buf.WriteString(sig)
	// buf.WriteString("\n\n")
	for _, part := range sigParts {
		buf.WriteString(part)
		buf.WriteString("\n")
	}
	buf.WriteString("\n")

	b = buf.Bytes()
	return
}

func stringToRows(input string, rowlen int) (output []string) {
	output = make([]string, 0)

	if len(input) <= 76 {
		output = append(output, input)
	} else {
		substr := input[:]
		var row string
		done := false
		for {
			if len(substr) > 76 {
				row = substr[0:76]
				substr = substr[76:]
			} else {
				row = substr[:]
				done = true
			}
			output = append(output, row)
			if done {
				break
			}
		}
	}

	return
}

func (serv *Service) generateRandomName() {
	randBytes := make([]byte, 18, 18)
	read, err := rand.Read(randBytes)
	if err != nil {
		// we can't announce a scamp service without a unique name so bail out
		log.Fatalf("could not generate all rand bytes needed. only read %d of 18", read)
	}

	base64RandBytes := base64.StdEncoding.EncodeToString(randBytes)

	var buffer bytes.Buffer
	buffer.WriteString(serv.humanName)
	buffer.WriteString("-")
	buffer.WriteString(base64RandBytes[0:])
	serv.name = string(buffer.Bytes())
}

// createKubeLivenessFile creates an empty file in the defaultLivenessDirPath to facilitate
// kubernetes auto-scaling
// TODO: we should discuss moving the path to the liveness file to a config file (like soa.conf)
func (serv *Service) createKubeLivenessFile() error {
	if _, err := os.Stat(defaultLivenessDirPath); os.IsNotExist(err) {
		err = os.MkdirAll(defaultLivenessDirPath, 0755)
		if err != nil {
			return err
		}
	}

	file, err := os.Create(defaultLivenessDirPath + serv.humanName)
	if err != nil {
		return err
	}
	defer file.Close()
	return nil
}

func (serv *Service) removeKubeLivenessFile() error {
	path := defaultLivenessDirPath + serv.humanName
	err := os.Remove(path)
	if err != nil {
		return err
	}
	return nil
}
