version: 2

jobs:
  build:
    working_directory: /go/src/github.com/gudtech/scamp-go/
    docker:
      - image: circleci/golang:1.10.3
    steps:  
      - checkout
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "./scamp/Gopkg.lock" }}
          paths:
              - /go/src/github.com/gudtech/scamp-go/scamp/vendor
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: cd ./scamp && dep ensure -vendor-only
      - run: cd ./scamp && go build -v 
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "./scamp/Gopkg.lock" }}
          paths:
            - /go/src/github.com/gudtech/scamp-go/scamp/vendor
      - run: cd ./scamp && go test -v -race ./... 